import tkinter as tk
def calculate_sum():
 num1 = float(entry1.get())
 num2 = float(entry2.get())
 num3 = float(entry3.get())
 result.config(text=f"Sum: {num1 + num2 + num3}")
 result1.config(text=f"Difference: {num1 - num2 - num3}")
 result2.config(text=f"Multiplication: {num1 * num2 * num3}")
 result3.config(text=f"Division: {(num1 / num2) / num3}")
 result4.config(text=f"Diakrinousa: {(num2 * num2) - (4 * (num1 * num3))}")
root = tk.Tk()
tk.Label(root, text="Number 1:").pack()
entry1 = tk.Entry(root,width=40)
entry1.pack()
tk.Label(root, text="Number 2:").pack()
entry2 = tk.Entry(root,width=40)
entry2.pack()
tk.Label(root, text="Number 3:").pack()
entry3 = tk.Entry(root,width=40)
entry3.pack()
button = tk.Button(root, text="Calculate", command=calculate_sum,width=40)
button.pack()
result = tk.Label(root, text="Sum: ")
result1 = tk.Label(root, text="Difference: ")
result2 = tk.Label(root, text="Multiplication: ")
result3 = tk.Label(root, text="Division: ")
result4 = tk.Label(root, text="Diakrinousa: ")
result.pack()
result1.pack()
result2.pack()
result3.pack()
result4.pack()
root.mainloop()
